(source melpa)
(source marmalade)
(source "MELPA" "http://melpa.milkbox.net/packages/")

(depends-on "ac-cider-compliment")
(depends-on "ac-etags")
(depends-on "ac-slime")
(depends-on "auto-complete")
(depends-on "cider")
(depends-on "column-enforce-mode")
(depends-on "column-marker")
(depends-on "ecb")
(depends-on "elpy")
(depends-on "epc")
(depends-on "gtags")
(depends-on "jedi")
(depends-on "multi-term")
(depends-on "multi-web-mode")
(depends-on "pallet")
(depends-on "pde")
(depends-on "php-boris-minor-mode")
(depends-on "php-extras")
(depends-on "php-mode")
(depends-on "slime")
(depends-on "yaml-mode")
(depends-on "yasnippet")